# Generated by Django 4.1 on 2022-12-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_user_bio_user_birthday_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("vi", "Vietnamese")], max_length=2
            ),
        ),
    ]
