# Generated by Django 4.1 on 2023-01-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_review_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
