# Generated by Django 4.1 on 2022-12-19 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("house", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Room type",
            },
        ),
        migrations.RemoveField(
            model_name="house",
            name="street",
        ),
        migrations.AddField(
            model_name="house",
            name="address",
            field=models.TextField(default="abc", max_length=100),
        ),
        migrations.AddField(
            model_name="house",
            name="bathroomCount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="house",
            name="bedCount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="house",
            name="bedroomCount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="house",
            name="check_in",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="check_out",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="guestCount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="house",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="house",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="house.amenity"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="facilities",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="house.facility"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="room_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="house.roomtype",
                verbose_name="Room type",
            ),
        ),
    ]
