# Generated by Django 4.1 on 2022-12-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0003_alter_house_check_in_alter_house_check_out"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="bathroomCount",
            new_name="bathroom",
        ),
        migrations.RenameField(
            model_name="house",
            old_name="bedCount",
            new_name="bed",
        ),
        migrations.RenameField(
            model_name="house",
            old_name="bedroomCount",
            new_name="bedroom",
        ),
        migrations.RenameField(
            model_name="house",
            old_name="guestCount",
            new_name="guest",
        ),
        migrations.AlterField(
            model_name="house",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="house.roomtype",
                verbose_name="Room type",
            ),
        ),
    ]
