# Generated by Django 4.1 on 2022-12-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0004_rename_bathroomcount_house_bathroom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
    ]
