# Generated by Django 4.1 on 2023-01-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0006_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="room",
        ),
        migrations.AddField(
            model_name="photo",
            name="house",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="house.house",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(upload_to="house_photos"),
        ),
    ]
