# Generated by Django 4.1 on 2023-01-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0008_alter_house_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
