# Generated by Django 4.1 on 2023-01-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0009_alter_amenity_updated_on_alter_facility_updated_on_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RoomType",
            new_name="HouseType",
        ),
        migrations.RenameField(
            model_name="house",
            old_name="room_type",
            new_name="house_type",
        ),
    ]
