# Generated by Django 4.1 on 2023-01-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0010_rename_roomtype_housetype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="housetype",
            options={"verbose_name": "House type"},
        ),
        migrations.AlterField(
            model_name="house",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="houses", to="house.amenity"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="facilities",
            field=models.ManyToManyField(
                blank=True, related_name="houses", to="house.facility"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="house_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="house.housetype",
                verbose_name="House type",
            ),
        ),
    ]
