# Generated by Django 4.1 on 2023-01-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0011_alter_housetype_options_alter_house_amenities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="city",
            field=models.CharField(max_length=30),
        ),
    ]
