# Generated by Django 4.1 on 2023-01-06 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("house", "0013_alter_house_house_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
