# Generated by Django 4.1 on 2023-01-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_reservation_guest_alter_reservation_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedday",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
